In [1]:
import numpy as np

In [4]:
X = np.array([[1], [2], [3]])
W = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
B = np.array([[1], [2], [3], [4]])
print(W)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
A = np.dot(W, X)+B
print(A)

[[15]
 [34]
 [53]
 [72]]
